### ISSUE TITLE
Incorrect address used for lookup of token decimals

### ISSUE THREAD

**Issue by barnjamin** [wormhole-foundation/connect-sdk#348]
...

https://discord.com/channels/856079283104251944/857225885231611935/1210581191187636224

**Comment by mmaurello** [comment]
Thank you for creating the issue, here is a piece of code to quickly reproduce this problem when trying to redeem a transfer:
```
    const recoverTxid =
      '0xa14c6384021d6cb2646c677717297348ea4305164ccd62889dd64f6112f7992f';

    const vaa = await TokenTransfer.getTransferVaa(wh, recoverTxid);
    const { token, to } = vaa.payload;

    console.log('token', token);
    console.log('tokenAddress', token.address.toString());
    console.log('to', to);
    console.log('wh', wh);
    console.log('decimals', await wh.getDecimals(token.chain, token.address));
```
This is a transaction from Fantom to Moonbase Alpha and, when I'm trying to redeem it, I experience the problem. This code replicates what the sdk does in the `fromIdentifier` function [here](https://github.com/wormhole-foundation/connect-sdk/blob/main/connect/src/protocols/tokenTransfer.ts#L161), and you can see that the decimals are not correctly fetched due to the address conversion:
![image](https://github.com/wormhole-foundation/connect-sdk/assets/93129175/0eea0092-ce69-46c2-8c0b-ee51decde820)

As discussed in Discord, the issue also happens when getting the quote of a new transaction, where it uses the universal address for the lookup: https://github.com/wormhole-foundation/connect-sdk/blob/7baf15538c24eb7587840bc86dfe8338fa5787af/connect/src/protocols/tokenTransfer.ts#L382
